[configDB]
    host            = "localhost"
    port            = 5432
    user            = "lvntools"
    password        = "123456"
    dbname          = "lvn-tools"


[credentials]
    email           = "m.siddikov@gmail.com"
    password        = "6UTEAI38LxN5f4feQKW6lgtTybWsczHbQyEEr5ru"
    loginPm         = "lavinatech"
    passwordPm      = "RxHPcZ3Ep"