[configDB]
    host            = "localhost"
    port            = 5432
    user            = "my user"
    password        = "my strong password"
    dbname          = "my awsome db"

[server]
    addr            = "localhost:9000"
    cert = ""
    key = ""


[options]
    debugMessages          = true